name: Deploy to AWS S3 and CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.14.0

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Install Dependencies
      run: npm install -g npm@9.3.1

    - name: Build React App
      run: npm install && npm run build

    - name: Configure AWS Credentials
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region us-east-1

    - name: Deploy to AWS S3
      run: aws s3 sync build/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}

    - name: Invalidate CloudFront Cache
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION }} --paths "/*"

#    - name: Deploy to AWS S3
#      uses: aws-actions/aws-cli@v2
#      with:
#        args: |
#          s3 sync build/ s3://portfolio-app-ak
#          aws cloudfront create-invalidation --distribution-id E1CNQ8HCYLNWW3 --paths "/*"
#      env:
#        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
#        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
